export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const FETCH_COURSES = 'FETCH_COURSES';
export const LISTEN_TO_COURSE_CHAT=' LISTEN_TO_COURSE_CHAT';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';